### ISSUE TITLE
Config not working

### ISSUE THREAD

**Issue by metieske** [flammy/fsapi-remote#3]
Hi Flammy,

We decided to use our fsapi enabled radio again.
Now we want to use your nice web interface for fiddling with it.
I saw you changed a lot since last time.

The setup does not automatically dicover our radio.\
And if we try to add it manually we get the error "Index not found"

maybe you can show us an example of config.txt so we can create a config manually.

Also when we kind of edit the code and hardcode our radio in the page wont load and only power on / off and the volume buttons work.
we get however after every action an error:

Uncaught SyntaxError: Unexpected token <
xajax.responseProcessor.json @ xajax_core.js:145
xajax.responseReceived @ xajax_core.js:420
oRequest.request.onreadystatechange @ xajax_core.js:383  

Would be great to be able to fully use your web interface!

Keep up the good work!

**Comment by flammy** [comment]
Hi,

it looks like there is a problem with xajax.  I updated xajax to the latest version, so it does not work with older php-versions.

It works for me with PHP 5.4. Please check your PHP-Version.

**Comment by metieske** [comment]
Hi Flammy,

i've tried a different host and it seems to work better now!
Do you have any idea when you could have the config fixed?

We might be looking into adding a search function for internet radio into your dashboard.
If we manage to do it we'll send you the code!

**Comment by flammy** [comment]
This should be fixed with https://github.com/flammy/fsapi-remote/commit/4fcb27edc6ff5b95cb586664cde3a3e75a4aed17

It would be nice if you play around with the sample_ssdp.php file in the fsapi folder, to get the correct device type string for your device.

```
$ssdp->setDeviceType('ssdp:all');
```

should give you all devices responding to ssdp.

**Comment by flammy** [comment]
The original app searches for the same string. 

Is the original DOK app working for you?

If not is there another app for your device?

**Comment by metieske** [comment]
Hi Flammy,

your latest fix does indeed fix the config problem.
Thank you!
