### ISSUE TITLE
Fatal error: Class 'fsapi' not found

### ISSUE THREAD

**Issue by veso266** [flammy/fsapi-remote#6]
Hi when I try to run fsapi-remote I get: 
Fatal error: Class 'fsapi' not found in /home1/veso266/public_html/hama/fsapi/radio.php on line 75

hope you can fix it

Thanks for Anwsering and Best Regards

PS: Do you think you could make a release with everything included just download into wwwroot
PPS: There is no fsapi.php, radio.php and ssdp.php in fsapi so I took them out of src dir (is this right?)

**Comment by flammy** [comment]
I am working on a new release, which will shipped as whole package.

**Comment by flammy** [comment]
I just made an artifact of the current release:

https://github.com/flammy/fsapi-remote/releases/download/2.0/fsapi-remote-2.0.zip

There is everything bundled you need. Please check if the new release solves your problem.

**Comment by flammy** [comment]
No answer since January - I just close the issue because the issue refers to an old release.

If you have problems with the new release feel free to open a new issue.
